version: "2.2"
services:
  create-escert:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ./config/:/usr/share/elasticsearch/config/
    user: "0"
    command: >
      bash -c '
        create_certificate() {
          if [ ! -f config/certs/ca.zip ]; then
            echo "================================================"
            echo "Creating CA";
            bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
            unzip config/certs/ca.zip -d config/certs;
            echo "================================================"
            echo ""
          fi;

          if [ ! -f config/certs/certs.zip ]; then
            
            echo "================================================"
            echo "Createing Elastic Search Instances yml";
            echo -ne "#this is instances.yml for Elastic Search
            instances:
              - name: es01
                dns:
                  - es01
                  - localhost
                ip:
                  - 127.0.0.1
            " | sed "s/^[\t]*//" > config/certs/instances.yml;
            echo "================================================"
            echo ""

            echo "================================================"
            echo "Creating certs";
            bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
            unzip config/certs/certs.zip -d config/certs;
            echo "================================================"
            echo ""

          fi;
        }

        if [ ! -d config/certs ]; then
          echo "================================================"
          echo "Creating config/certs directory";
          mkdir -p config/certs;
          echo "================================================"
          echo ""
        fi;

        create_certificate;

        echo "================================================"
        echo "Createing logstash.yml";
        echo -ne "#this is logstash.yml
        ELASTICSEARCH_PASSWORD: logstash_internal
        ELASTICSEARCH_USERNAME: logstash_internal
        ES_JAVA_OPTS: -Xmx2048m -Xms2048m
        http.host: \"0.0.0.0\"
        path.config: \"/usr/share/logstash/config/logstash.conf\"
        xpack.monitoring.elasticsearch.url: \"https://es01:9200\"
        xpack.monitoring.enabled: \"false\"
        " | sed "s/^[ \t]*//" > config/logstash.yml;
        echo "================================================"
        echo ""
        
        echo "================================================"
        echo "Createing kibana.yml";
        echo -ne "#this is kibana.yml
        server.name: kibana
        server.host: \"0.0.0.0\"
        server.port: \"5601\"
        elasticsearch.hosts: [\"https://es01:9200\"]
        elasticsearch.username: kibana_system
        elasticsearch.password: kibana
        elasticsearch.ssl.certificate: config/certs/es01.crt
        elasticsearch.ssl.key: config/certs/es01.key
        elasticsearch.ssl.certificateAuthorities: config/certs/ca.crt
        " | sed "s/^[ \t]*//" > config/kibana.yml;
        echo "================================================"
        echo ""
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120
