apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: es01
  name: es01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/sample-pylogger-azblob-eskibana-default: "true"
        io.kompose.service: es01
    spec:
      containers:
        - name: es01
          image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
          env:
            - name: network.host
              value: "0.0.0.0"
            - name: http.port
              value: "9200"
            - name: transport.host
              value: localhost
            - name: transport.port
              value: "9300"
            - name: ELASTIC_PASSWORD
              value: elastic
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.initial_master_nodes
              value: es01
            - name: cluster.name
              value: docker-cluster
            - name: node.name
              value: es01
            - name: xpack.license.self_generated.type
              value: basic
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.security.http.ssl.certificate
              value: certs/es01.crt
            - name: xpack.security.http.ssl.certificate_authorities
              value: certs/ca.crt
            - name: xpack.security.http.ssl.enabled
              value: "true"
            - name: xpack.security.http.ssl.key
              value: certs/es01.key
            - name: xpack.security.transport.ssl.certificate
              value: certs/es01.crt
            - name: xpack.security.transport.ssl.certificate_authorities
              value: certs/ca.crt
            - name: xpack.security.transport.ssl.enabled
              value: "true"
            - name: xpack.security.transport.ssl.key
              value: certs/es01.key
            - name: xpack.security.transport.ssl.verification_mode
              value: certificate
            - name: xpack.security.enrollment.enabled
              value: "true"
          securityContext:
            privileged: true
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - 'curl -s --cacert config/certs/ca.crt https://localhost:9200 | grep -q "missing authentication credentials"'
            failureThreshold: 120
            periodSeconds: 10
            timeoutSeconds: 10
            initialDelaySeconds: 100
          ports:
            - containerPort: 9200
              hostPort: 9200
              protocol: TCP
          resources:
            limits:
              memory: "1073741824"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/config/certs
              name: certs
      restartPolicy: Always
      volumes:
        - name: certs
          configMap:
            name: es-certs-configmap
status: {}
