apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/sample-pylogger-azblob-eskibana-default: "true"
        io.kompose.service: logstash
    spec:
      containers:
        - args:
            - bash
            - -c
            - 'logstash-plugin install logstash-input-azure_blob_storage && logstash -f /usr/share/logstash/config/logstash.conf '
          env:
            # - name: ES_JAVA_OPTS
            #   value: -Xmx2048m -Xms2048m"
            # - name: http.host
            #   value: 0.0.0.0
            # - name: path.config
            #   value: /usr/share/logstash/config/logstash.conf
            # - name: xpack.monitoring.elasticsearch.url
            #   value: https://es01:9200
            # - name: xpack.monitoring.enabled
            #   value: "false"
          image: logstash:8.9.2
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - 'curl -s -I http://localhost:9600 | grep -q "HTTP/1.1 200 OK"'
            failureThreshold: 120
            periodSeconds: 10
            timeoutSeconds: 10
          name: logstash
          ports:
            - containerPort: 9600
              hostPort: 9600
              protocol: TCP
          resources: {}
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /usr/share/logstash/config/certs
              name: certs
            - mountPath: /usr/share/logstash/config/logstash.conf   # NOTE: LogStash Config File should be placed in the [/usr/share/logstash/config/logstash.conf]"
              name: certs
              subPath: logstash.conf
            - mountPath: /usr/share/logstash/config/logstash.yml   # NOTE: LogStash YAML File should be placed in the [/usr/share/logstash/config/logstash.yml]"
              name: certs
              subPath: logstash.yml
      restartPolicy: Always
      volumes:
        - name: certs
          configMap:
            name: es-certs-configmap
status: {}